/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Control: typeof import('./src/components/Control.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
  }
}
