/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Navbar: typeof import('./src/components/navbar.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
  }
}
